feat: solve exercise01
asGabriel/associate-software-engineer pull request #1
Opened 2024-01-23 01:53 UTC by asGabriel

2024-01-23 01:58 UTC, antoniomatiolijr requested changes

2024-01-23 01:58 UTC, antoniomatiolijr commented on exercise01.js
> +}
- Arrumar a formula
- a função deve indicar um verbo
- retorno direto

2024-01-23 01:58 UTC, antoniomatiolijr commented on exercise01.js
> +console.log(perimeter(length, width));
Adicionar uma linha no final do arquivo

2024-01-23 03:24 UTC, antoniomatiolijr requested changes

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise01.js
> +console.log(`The rectangle area ia ${calculateArea(length, width)}`);
`The rectangle area is

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise01.js
> +    return (length * width);
return 2 * (length + width);

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise01.js
> +    return (length + width)
(length * width)

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise01.js
> +    return (length + width)
Não precisa dos parenteses

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise01.js
> +    return (length * width);
Não precisa dos parenteses

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise02.js
> +    allStrings = allStrings.concat(word);
allStrings += word;

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise03.js
> +var highestNumber = 0;
var? nunca vi

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise03.js
> +for (let property in numericObject) {
const property

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise03.js
> +function compare(number, numberToCompare) {
compare não descreve o que vc faz, caso vc mantenha o maior numero vc deve descrever isso no nome da função

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise03.js
> +    }
```typescript

if (condicao) {
     return numberToCompare;
}

return number;

```

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise04.js
> +    number += 1;
number++;

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise05.js
> +} while (option != 10);
`<=`

2024-01-23 03:24 UTC, antoniomatiolijr commented on exercise06.js
> +}
cria uma linha ao final do arquivo

2024-01-23 03:24 UTC, antoniomatiolijr commented on mock.js
> +export { randomStrings, numericObject }
enter break line

2024-01-24 12:23 UTC, antoniomatiolijr requested changes

2024-01-24 12:23 UTC, antoniomatiolijr commented on exercise07.js
> +console.log(filteredStudents);
só adicionar a break line

2024-01-24 12:23 UTC, antoniomatiolijr commented on mock.js
> +export { randomStrings, numericObject, students }
break line

2024-01-24 12:23 UTC, antoniomatiolijr commented on exercise08.js
> +import { students } from "./mock.js";
Primeira coisa que vc ai fazer é calcular a média de idade.
- Faz um reduce depois dividi pela quantidade de estudantes, direto.

Com a média vc vai usar isso para filtrar e trazer somente os estudantes a cima da média.

2024-01-24 12:25 UTC, antoniomatiolijr requested changes

2024-01-24 12:25 UTC, antoniomatiolijr commented on exercise08.js
> +let averageStudentAge = [];
ponto importante eu vi que ao longo do exercício vc criou esse array, depois foi populando ele (vc não precisa fazer essa separação de age, pq isso é gastar processamento atoa) e depois transformou em inteiro.

ou seja vc criou um side effect no sistema, caso precise fazer isso sempre crie uma variável nova que armazena o inteiro

2024-01-25 02:30 UTC, asGabriel commented on exercise01.js
> +console.log(`The rectangle area ia ${calculateArea(length, width)}`);
feito

2024-01-25 02:31 UTC, asGabriel commented on exercise01.js
> +    return (length * width);
feito

2024-01-25 02:31 UTC, asGabriel commented on exercise01.js
> +    return (length + width)
feito

2024-01-25 02:31 UTC, asGabriel commented on exercise02.js
> +    allStrings = allStrings.concat(word);
feito

2024-01-25 02:31 UTC, asGabriel commented on exercise03.js
> +var highestNumber = 0;
feito rsrsrs

2024-01-25 02:31 UTC, asGabriel commented on exercise03.js
> +for (let property in numericObject) {
feito

2024-01-25 02:31 UTC, asGabriel commented on exercise03.js
> +function compare(number, numberToCompare) {
feito

2024-01-25 02:33 UTC, asGabriel commented on exercise03.js
> +    }
alterei para um operador ternário ai mata em uma linha

2024-01-25 02:34 UTC, asGabriel commented on exercise04.js
> +    number += 1;
feito

2024-01-25 02:35 UTC, asGabriel commented on exercise05.js
> +} while (option != 10);
feito

2024-01-25 22:33 UTC, asGabriel commented on exercise08.js
> +import { students } from "./mock.js";
feito

2024-01-26 05:03 UTC, antoniomatiolijr requested changes

2024-01-26 05:03 UTC, antoniomatiolijr commented on exercise01.js
> +    return 2 * length + width;
lembra de por um parenteses para garantir que está sendo executado corretamente.

Essa formula vai dar errado pois ele vai executar a multiplicação de 2 * length e depois somar width, ou seja, não retornando o que queremos.

2024-01-26 05:03 UTC, antoniomatiolijr commented on exercise02.js
> +for (let word of randomStrings) {
const word (não usa let pois word não vai ser alterada)

2024-01-26 05:03 UTC, antoniomatiolijr commented on exercise02.js
> +for (let word of randomStrings) {
Com isso vc economiza alocação de memoria desnecessária, pois toda variável que é mutável ela precisa pré alocar alguns bytes a mais para se preparar para receber valores possivelmente maiores.

2024-01-26 05:03 UTC, antoniomatiolijr commented on exercise03.js
> +function getGreaterNumber(number, numberToCompare) {
uma sugestão é padronizar os usos de function, ou usar dessa forma do jeito clássico como fez, ou com arrowFunction

2024-01-26 05:03 UTC, antoniomatiolijr commented on exercise06.js
> +const color = "black";
constante como essa devem ser maiusculas, ou seja, const COLOR = "black";

2024-01-26 05:03 UTC, antoniomatiolijr commented on exercise08.js
> +))/students.length;
faz a divisão em outra linha para ficar mais simples

2024-01-26 05:03 UTC, antoniomatiolijr commented on exercise08.js
> +    (sum, obj) => {
renomeia obj para student, deixa mais claro

2024-01-26 05:03 UTC, antoniomatiolijr commented on exercise09.js
> +}
para não ter que usar o today, adiciona no seu mock o birthDate e usa isso para converter.

algo como para cada student, birthdate: "YYYY-MM-DD"

2024-01-26 05:03 UTC, antoniomatiolijr commented on exercise09.js
> +})
```typescript
const studentsWithFormatedDate = students.map((student) => {
    return {
        ...student,
        longDateFormat: convertInLegibleData(date, student.age)
    }
})

// vc sempre adiciona uma nova propriedade pois assim vc não perde a informação original no caminho caso precise em algum outro local do código.

2024-01-26 05:03 UTC, antoniomatiolijr commented on exercise09.js
> +}
```typescript
function getMonthName(monthNumber) {
    const monthNames = {
        0: "Janeiro",
        1: "Fevereiro",
        2: "Março",
        3: "Abril",
        4: "Maio",
        5: "Junho",
        6: "Julho",
        7: "Agosto",
        8: "Setembro",
        9: "Outubro",
        10: "Novembro",
        11: "Dezembro"
    };

    if (monthNumber in monthNames) {
        return monthNames[monthNumber];
    }
    return "Mês inválido.";
}

```

2024-01-27 19:50 UTC, asGabriel commented on exercise09.js
> +}
Adriano me mostrou o Intl.DateTimeFormat ai anulei essa função. Mas aderi a sua função que ficou mais direta que o switch case.

2024-01-28 14:21 UTC, antoniomatiolijr requested changes

2024-01-28 14:21 UTC, antoniomatiolijr commented on exercise03.js
> +    highestNumber = highestNumber > numericObject[property] ? highestNumber : numericObject[property]
```typescript

if (numericObject[property] > highestNumber) {
    highestNumber = numericObject[property]
}
```

2024-01-28 14:21 UTC, antoniomatiolijr commented on exercise03.js
> +let highestNumber = 0;
```typescript

let highestNumber = -Infinity; 

// se vc começar com zero e os valores do mock forem negativos vc não vai acertar o resultado


```

2024-01-28 14:21 UTC, antoniomatiolijr commented on exercise08.js
> +const averageStudentsAge = sumStudentsAge/students.length;
```typescript
const averageStudentsAge = sumStudentsAge / students.length;
```

Está faltando espaço

2024-01-28 14:21 UTC, antoniomatiolijr commented on exercise09.js
> +})
```typescript

const studentsWithDate = students.map((student) => {
    return {
        ...student,
        longDateFormat: convertInLegibleData(student.birthDate)
    }
});

```

pode retornar direto

2024-01-28 14:21 UTC, antoniomatiolijr commented on exercise09.js
> +    const birthDateSplit = birthDate.split("-");
const birthDateObj = new Date (birthDate)

2024-01-28 14:21 UTC, antoniomatiolijr commented on exercise10.js
> +  return newStudent;
```typescript

return {
    ...student,
    daysUntilBirthDate: daysUntilBirthDate(student.birthDate),
  };
```

2024-01-28 14:21 UTC, antoniomatiolijr commented on exercise10.js
> +  const days = Math.round((new Date() - birthDateWithCurrentYear) / 86400000);
86400000 é sempre melhor splitar a conta e armazenar em constantes assim vc deixa claro o que é esse valor sem precisar adicionar um comentário

2024-01-30 19:06 UTC, antoniomatiolijr requested changes

2024-01-30 19:06 UTC, antoniomatiolijr commented on exercise10.js
> +    Math.round((new Date() - new Date(birthDateWithCurrentYear)) / (second * minute * hour * day));
vc pode criar uma função de conversão em um utils.date.js

2024-01-30 19:06 UTC, antoniomatiolijr commented on exercise10.js
> +  return days;
esse pode ser um ternário `return days > 0 ? days : -days;`

2024-01-30 19:06 UTC, antoniomatiolijr commented on exercise16.js
> +function greetings(name) {
Parametro padrão é quando vc determina um valor default para ela https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

2024-01-30 19:06 UTC, antoniomatiolijr commented on exercise18.js
> +function convertMilissecondsToDays(milissecondsDate) {
como eu falei acima da para ser uma função genérica que vc só chama ela

2024-01-30 19:06 UTC, antoniomatiolijr commented on exercise19.js
> +}
acho que ja vi essa função em outro exercício

2024-01-30 19:06 UTC, antoniomatiolijr commented on exercise19.js
> +      fullDateName: convertInLegibleData(student.birthDate),
pelo que entendi quem pode falhar é a função convertInLegibleData, ou seja, nela que deveria estar o try/catch

2024-02-05 12:35 UTC, antoniomatiolijr requested changes

2024-02-05 12:35 UTC, antoniomatiolijr commented on exercise03.js
> +    highestNumber = highestNumber > numericObject[property] ? highestNumber : numericObject[property]
acho que não subiu

2024-02-05 12:35 UTC, antoniomatiolijr commented on exercise26.js
> +async function executePromise(responseMessage, TimeToTimeout) {
`TIME_TO_TIMEOUT` constantes seguem o padrão de tudo maisculo

2024-02-05 12:35 UTC, antoniomatiolijr commented on utils/api.js
> +export { PORT, API_URL, clientsEndpoint }
ta faltando um enter

2024-02-06 12:37 UTC, antoniomatiolijr requested changes

2024-02-06 12:37 UTC, antoniomatiolijr commented on utils/date.js
> +    return {error: error.message};
throw new Error(error)

2024-02-06 12:37 UTC, antoniomatiolijr commented on exercise19.js
> +  const fullDateName = convertInLegibleData(student.birthDate);
ai sim da para fazer um try/catch onde no catch vc loga o erro, dado que eu fiz uma alteração la em baixo

2024-02-07 12:26 UTC, antoniomatiolijr requested changes

2024-02-07 12:26 UTC, antoniomatiolijr commented on exercise03.js
> +    highestNumber = highestNumber > numericObject[property] ? highestNumber : numericObject[property]
acho que só falta esse

2024-02-07 12:26 UTC, antoniomatiolijr commented on exercise19.js
> +    };
se deu erro vc não retorna, vc tem duas opções ai vai depender da regra de negócio:

1. Vc da um throw/da um retorno de que falhou a requisição por algum motivo
2. ou vc da um continue, para pular somente o caso que deu errado e depois caso o pessoal queira investigar vai olhar o Log

2024-02-07 12:26 UTC, antoniomatiolijr commented on utils/date.js
> +const daysUntilBirthDate = (birthDate) => {
aqui n é birthDate né, aqui é daysUntilDate, pq pode ser genérico e vc usar em qualquer lugar

2024-02-07 17:28 UTC, asGabriel commented on exercise19.js
> +    };
Entendi. Eu adicionei esse return para tentar tratar o fato de entrar um 'undefined' no array quando ocorre o erro. 
Veja se o que eu fiz faz sentido, adicionei um filter na função para limpar os undefined, dessa forma os erros serão acumulados somente no log mesmo; 
- Não joguei um throw para não parar o map e manter a ideia do log funcional

2024-02-08 03:27 UTC, antoniomatiolijr requested changes

2024-02-08 03:27 UTC, antoniomatiolijr commented on exercise19.js
> +  .filter((student) => student !== undefined);
.filter((student) => student);

2024-02-08 03:27 UTC, antoniomatiolijr commented on utils/date.js
> +  const birthDateWithCurrentYear = new Date(date).setFullYear(
birthDate?

2024-02-08 13:13 UTC, antoniomatiolijr requested changes

2024-02-08 13:13 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/teste-nivelamento/exercise19.js
> +      };
Só uma dica quando a variável e a propriedade do objeto tem o mesmo nome, pode ficar mais simples como o de baixo.

```typescript

return {
        ...student,
        fullDateName,
      };
```

2024-02-08 13:49 UTC, asGabriel commented on software-engineer-I/fc-1/javascript/teste-nivelamento/exercise19.js
> +      };
boa, não sabia dessa.

2024-02-08 15:20 UTC, antoniomatiolijr approved these changes

2024-02-08 15:20 UTC, merged