Feat/fc1/js/modulo7/topico2
asGabriel/associate-software-engineer pull request #3
Opened 2024-02-13 12:47 UTC by asGabriel

2024-02-14 12:26 UTC, antoniomatiolijr requested changes
Parece que os exercicios do topico 1 vieram junto

2024-02-16 01:31 UTC, antoniomatiolijr requested changes

2024-02-16 01:31 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-7/topico-2/exercise02.js
> +  }
vc pode transformar esse meio em uma função e deixar dinamico para receber como parametro a o elemento que vc quiser pq ai fica reutilizável

2024-02-16 01:31 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-7/topico-2/exercise03.js
> +  const randomColor = "#" + (Math.floor(Math.random() * 900000) + 100000);
cria uma função para gerar cores.

2024-02-16 01:31 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-7/topico-2/exercise04.js
> +    alert("Form has been succesfully sent");
cria uma função que recebe o input como parametro

2024-02-16 01:31 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-7/topico-2/exercise05.js
> +  ulHTML.append(newItemList);
pode ser uma função

2024-02-16 01:31 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-7/topico-2/exercise06.js
> +  console.log(spanHTML.textContent);
remover

2024-02-16 01:31 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-7/topico-2/exercise08.js
> +    : (divToMoveHTML.style.left = "100px");
função tb

2024-02-16 01:31 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-7/topico-2/exercise10.js
> +inputHTML.addEventListener("keydown", (key) => {
vc pode chamar de event, ou descontruir para ficar mais simples.

("keydown", ( { key  } )

2024-02-16 12:36 UTC, antoniomatiolijr requested changes

2024-02-16 12:36 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-7/topico-2/exercise03.js
> +  return randomColor = "#" + (Math.floor(Math.random() * 900000) + 100000);
```typescript
return `#${(Math.floor(Math.random() * 900000) + 100000)}`;

```

2024-02-16 12:36 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-7/topico-2/exercise03.js
> +  return randomColor = "#" + (Math.floor(Math.random() * 900000) + 100000);
vc não precisa declarar a variável pq vc já está retornando

2024-02-16 14:23 UTC, asGabriel commented on software-engineer-I/fc-1/javascript/modulo-7/topico-2/exercise03.js
> +  return randomColor = "#" + (Math.floor(Math.random() * 900000) + 100000);
my bad. copy n paste é foda esqueci de tirar

2024-02-17 03:33 UTC, antoniomatiolijr requested changes

2024-02-17 03:33 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-7/topico-2/exercise03.js
> +  return "#" + (Math.floor(Math.random() * 900000) + 100000);
template string

2024-02-19 19:08 UTC, antoniomatiolijr approved these changes

2024-02-19 19:09 UTC, merged